---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
spec:
  storageClassName: tank-nfs-config-sc
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi