---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tank-nfs
  resources:
    requests:
      storage: 100Mi