apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 20m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1002
            runAsNonRoot: true
            fsGroup: 1002
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.4@sha256:85f185207a81ec03e84b8302db06f1694c533c99e0efdb2acf0316d554d332e3

    hostname: torrent # needed for an static IP

    env:
      TZ: ${TIMEZONE}
      QBITTORRENT__PORT: &port 80
      QBITTORRENT__BT_PORT: &port-bt 18289

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        controller: main
        # type: LoadBalancer
        enabled: true
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          # ingressclass.kubernetes.io/is-default-class: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
          hajimari.io/info: Torrent Downloader
          hajimari.io/group: media
        hosts:
        - host: &externalhost "torrent.pub.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: http
        - host: &internalhost "torrent.home.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *externalhost
          - *internalhost

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-pvc
      downloads:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/downloads
        mountPath: /downloads
      media:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/media
        globalMounts:
          - path: /media
      storage:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/storage
        globalMounts:
          - path: /storage
      incomplete:
        enabled: true
        type: emptyDir

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi