---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: download
spec:
  interval: 20m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: serveradmin
            runAsGroup: 1002
            fsGroup: 1002
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [100]
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.2@sha256:fedb62126c82ae0c7192e9052633411294a27e9c233613c03b0a8d168d160040
    env:
      TZ: ${TIMEZONE}
      QBITTORRENT__PORT: &port 80
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host torrent.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: serveradmin
      runAsGroup: 1002
      fsGroup: 1002
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [100]
    podAnnotations:
      setGateway: "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
    persistence:
      downloads:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/downloads
        mountPath: /downloads
      media:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/media
        globalMounts:
          - path: /media
      storage:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/storage
        globalMounts:
          - path: /storage
      incomplete:
        enabled: true
        type: emptyDir
    volumes:
    - name: config-nfs
      persistentVolumeClaim:
        claimName: qbittorrent-config-pvc
