apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.6.2@sha256:fedb62126c82ae0c7192e9052633411294a27e9c233613c03b0a8d168d160040

    hostname: torrent # needed for an static IP

    env:
      TZ: ${TIMEZONE}
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__BT_PORT: &port-bt 18289

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
          hajimari.io/info: Torrent Downloader
          hajimari.io/group: media
        hosts:
        - host: &host "torrent.pub.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-pvc
      downloads:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/downloads
        mountPath: /downloads
      media:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/media
        globalMounts:
          - path: /media
      storage:
        enabled: true
        type: nfs
        server: "192.168.1.50"
        path: /tank/storage
        globalMounts:
          - path: /storage
      incomplete:
        enabled: true
        type: emptyDir
    podSecurityContext:
      runAsUser: serveradmin
      runAsGroup: 1002
      fsGroup: 1002
      supplementalGroups:
      - 65536

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi