---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te"
