---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-config-pvc
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 10M