---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: download-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0
    DNS: ${DOWNLOAD_GATEWAY_VPN_VXLAN}.1
    routed_namespaces:
      - download
    settings:
      VXLAN_IP_NETWORK: ${DOWNLOAD_GATEWAY_VPN_VXLAN}
      VPN_INTERFACE: tun0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "1194"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "${CLUSTER_CIDR} ${SERVICE_CIDR}"
      VPN_LOCAL_CIDRS: "${DOWNLOAD_GATEWAY_VPN_VXLAN}.0/24 ${CLUSTER_CIDR} ${SERVICE_CIDR}"
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image: 
            repository: qmcgaw/gluetun
            tag: v3.36.0
        env:
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        envFrom:
        - secretRef:
            name: download-gateway-secret
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 1194
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: ${CLUSTER_CIDR}
            - to:
                - ipBlock:
                    cidr: ${SERVICE_CIDR}