apiVersion: v1
kind: Secret
metadata:
    name: download-gateway-secret
    namespace: download
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:m8L9IKKfuKZuYk/pQb7q+LzMFsY6+07JiYW11SbtHuXKkQzP2nQHc28iwpc=,iv:IzgdoGPCRo/PonMHcwPt/Tq9l8utbXw14n/sZZn03/Q=,tag:HUQjgdAfTQ6m5Mn35VaDHQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:kYou23PXiN2SjhGrt7+VcHAkVv/v981N1uXzIXKBeUPVgFIimDSimz0IYdM=,iv:OQuBc0+HEalZFC6Pw/k3ETMT6OQ07lPBFsCMy9MepP8=,tag:Cg312hPCbIpk704+NpSOkg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:jpFw1RJVgaCWyMg=,iv:ROdRS1MLc5VAO79a5gcDUfMXY7lXHDE2I6a6x/KoEjQ=,tag:DQadSyGGwkPNmMXYX1JlDA==,type:str]
    #ENC[AES256_GCM,data:0QBFfcphwUhJ/rfiWC9nKHTsFuwYDPVWTAyU/HpmweIrEYGwkD3YVJ9AdH9zud4WS7R06h5DpQXVdQ0=,iv:kTvnQL1or5jLn81Ep+OfiVzQ4jg8zav1liSqpB5XFjE=,tag:CrwpxHvucVfNWU05PlSHdQ==,type:comment]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:tcBgacd9,iv:bhtUfylSmg9cttvoINUrlfHzElD1vuc2lQfktRZGS9Y=,tag:EAPkfwtO56dflhqL9WgTZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdVNmTExPL2I2V2xEdzJY
            ZXd3RktUTkxEWmlvYVI1eW5WNS9wTklKZ21rCjlXL0gyNzhFaDJOYXlabFhleFVl
            OEFyRDRsN25qampzV3IzVE9GZVJPRTgKLS0tIHFZZWYyUkhWaVdYb1Q1NkJhd0E3
            cWt5cVpWR3RhUVBIREVPNzZrbnBXVkEKchNkUKjdKqDaLU2CI0DvdGISaroBNCt2
            Nev0jCDWMt/ok4nJeUDx4s7hmwFs5peUwet0gUqsdYWR3LfpfUUxZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T22:27:11Z"
    mac: ENC[AES256_GCM,data:jjNP5HcvY0ltrvJHmRAtiePEmgLinUJfNaEy5XkOK77vvnSrZG2Ts5BFHpgAhaA0R6ZjdEFZ21q3SMtqkcpSSUrfca8WsKvsw7wScnsxHkpixC+YMoEJQ+CQ2FIhyT/HkB8u+3yVpLzOl5+c/PBV4nyg2snD57T/l+eGF/9dAts=,iv:EOXqPOmwsTM1YUuZ/MzOTfz2ppO5A8j/MMFEU0Kyzx8=,tag:qaJH/WHKKvxkpK0rCUClxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
