ansible_become_pass: ENC[AES256_GCM,data:Kaw+IGTm3Tk5,iv:YkqhbAfz2s2YkyRrGohHrvOXs6QAe8joPJ6dZFN0ZL4=,tag:qByzf8ZdN/zK1hQmeGvdAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSFJuS3Brb2VwU3BuSG8z
            dWwwLzdzOEN4NStzSFdySHBseG5tTm5CQUZJCm9XSGhhZmhtc2N0UzlUdGVJbkp5
            SnRwendFUlRnV0hDZ1Y0RnpyVWpmUncKLS0tIFoweG0ra21nb2M5K3JOSXBlQkc0
            YXZVK1hmWDVsLy9JblY3bjRhb2RZcUEKo3/K1kzuScYeTfnffbKqsDFieEFmpW5P
            QWKVkdzURSY2f8Ln7VITcKDHcFtbwASSvdrwNqmkaih8nDgi7MwBQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T11:04:22Z"
    mac: ENC[AES256_GCM,data:pvraukoIm1XOfztqxk6ReXL3cKMhitylO0smwpCnFNq4KW92Gb1Q2140uz7uVDtl7/Z/j1DCYvtr+NOCalf5Lz3I1u0Zn3PNokV5Kr576rKY2AnGxn2jHzbUjUyoTe0a7sfigLobwGrzIi5VbDCpubHmTIV1o6apvlwssdlMWV8=,iv:vamMNJ4lNrpz7ixeAq9svIk5tvSjAgL9lTQI5g5FP9g=,tag:cn7WZdeDOWTPWnBKfatDDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
