ansible_become_pass: ENC[AES256_GCM,data:RM9iBz22nV/V,iv:YTszsvwf9MpT8BAwC0efKSE4sorGyfFwE4Fd0qzsBdo=,tag:9ffJNak0Aom6Yy4BXEhDHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc0I3dHZqd1RpRWY3ZU40
            aEZISDBjVU8xYTNUOE5tMVplY2hSSlE2cXpzCk1xVHZnOURkZGpHSkk5Q0toaWdI
            eVQwSDh2c3NuQk1OWFZJK3h3aXk3Z1UKLS0tIExhY1BNT2dvbHQzaU8zK2Q0aXhX
            RlNZbW9aZnJvSUZjdzR1eEtnalR6SVkKIFsEOqmqzxAGweBGyCEpNtHX9mPoslL5
            lXi6hD+RSqjZpHvhKeMTPAiGSXcpgoL9QBczQsEs0MTWT+E27YUXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T08:55:15Z"
    mac: ENC[AES256_GCM,data:6m/xoCKdby6u33uVn//vg0aVTYaLjoDJOxsyxn+eYN/RRDgl8ZFn4Hl7qswN+ipqTiG/Uo8WqVlUQf9rlx8hev3Ab8hSGubNuYFOtAQspfCBz+4fgwbMchI7u4HiUVlZQfB0Vhh8PR/9IG31zsNdNGPNY84hd1QS0OJ/Hm+Xt5s=,iv:Gm+EjdOotHZAxBUoHoXb/QGfMrXGwjT5K/KDQZCUxqE=,tag:LAKmnZM1xotKHmGp3SA4Uw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
