ansible_become_pass: ENC[AES256_GCM,data:IdlMt1Gycrwm,iv:Oxni6CnuoWc8FicT2QFBpT/qzIhu2iBLjVqiLDfpMX0=,tag:HcubEICNgAQhn/R02etSQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYjJDRXlPY2JhbWh4VVdC
            ZnZKZGMwN2RDZ29lZFE5QXV3dVZxNFZpazFzCnQ2K0c3MGN1ZnM4bU5Fdjg3Q1E1
            UzdLVllpK3BlUE8yVE55aEZ4N2tobzQKLS0tIGkyamIzSjViMW53VmNLVzVHVnFm
            UHdZb0MvZEszaVFqb2l1UC8rNWhPREUKJ329NfFHOGZyrpVZMvTfnpyUQF6NcYA+
            7bmbeF5x8+S/Q3FpcVh/BXaPFSedjVNV3paE8LDfiL/6bTr16xbzQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T09:36:41Z"
    mac: ENC[AES256_GCM,data:pBXKtP3SO7V8pqxGEI+W9AC2ydVMm3dlPv52BeM7EcySKrxvjZXtfgj/NiAQp6soNzw0wu719BQ0PwxWgvhTWI7yBH8hIR647PzOjlvQGHAnaBLrUcLtOYMSD9T+Hm+hqVDBQ+kMeUB5jbjrqtE/MsgnTQCIJSZk8VL4iWQEu4E=,iv:Ay7gIUiBuum1CabKGiDYhKipAx4cuMK+AyDgRxjOUHw=,tag:GwLJxnSDdqdXkSmqqwXTjg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
