---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tank-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.1.50"
  share: /tank
  readOnly: "false"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
