apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZML4oNlgJ6ZJeKAQMo7ogh+EqjmcsDw+dla0xsr4+UXR4JRii70HyQ==,iv:DkMYVyyzQ1vj5TFIk1t45/npmqtibxQ1lbEw8fB3sQE=,tag:bY3brJMi2v8fPQLCPCo8+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU2J0WkU2aGlkQTlDYU00
            VUI3a2xLdTJjeGNQZnhseGJMWHhWdSsxN1hZClRodGRsQ0lSL3RncEZrTC9JeFlL
            YkpRdERiT2dDMTlZdDRsZzJlZXhmK3MKLS0tIERxa0o2ZXRhOW1TV1NBRWZmM0t5
            OGJHVzNIZkRJZExDVGdmaXU5ZzYxNHMKWElrJbNvrDQA4w7Ec2tA81vAti6993dq
            zvvVnA2uJAa7AZ3nKU3SsdhrHWeXCCTSLcPjR5MayFfJVU0IaKZCHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T11:05:44Z"
    mac: ENC[AES256_GCM,data:RpWXBf0SBL2jb3hrGaS2m95y/gy97ayvPe0Lru167eyzfNk5z78M7uqGSak1E0o4YEzFiHmdEtjAQgIm3Ygdm4924fSN+uCXa+quxsZ7/nUkDQnVRUMD4ZhugJ6DkhbMxmHKouSeRU5UjQgjYelr1uB9qgdOJE82eSJqoOgj0+Q=,iv:C2RnGunKdj8E8/RFgFhso1l1xDcugUyRnGqd4I4BejA=,tag:SYQPa72t87VpsGiH8Gp8Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
