---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app download-gateway
  namespace: flux-system
spec:
  targetNamespace: vpn
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/vpn/download-gateway/app
  prune: true
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: download-gateway
      namespace: vpn