apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:186qvfe8yfMUsOmL21Eq/oWp87zwCmVNJ9byU5rgLm/nETEL7eCtdY6kJg2hEm6tZozDWICvO86jKbio,iv:GJCvDSLut/OKz5uTE06DXhDhiEbgPC1WmwTUg7XkV7M=,tag:2YllyWIhntwoPKsU1Xm6Fg==,type:str]
    username: ENC[AES256_GCM,data:LfAUW00=,iv:3fbAW3Ph9d8Y5CIeoeuvm2Bg6G4Ws9RZLEJp5MdZMLs=,tag:PSjEW3GBVdNSpW9uNaWfvw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ3RXYnd3K3BHSzhUV3ox
            Y0paVnR4anJJMFpjWEk2KzJkaXZkUDhSWmxnClM4TlFOelI2YlJqU0I0QUNKek96
            RjBCcVZzdmdhSU4xR1FYemlFQkdYbGcKLS0tIEJJOW9XUWUvU1lXS1J3Wk1oQzZI
            QU9TTVBZcDFDTnRFZUNqNTg0SDZOR0UKuNIsi0lY5NPPd34P5YZGLmq0EQpmC/La
            lUKmrrbRxnUBoMdzkT4UR2r/vfF7yGWgWBJvIsSWP9YSoBg7cTCzug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T08:56:58Z"
    mac: ENC[AES256_GCM,data:7TqYCB+1W/zf1oCrvAtNqoVxs8ZPZ7EYNgtjc/X+Uxr8bGRM32KFxkT5fHfDME3JPnkXaTdDIA45MNtQXbY7k601PYWe7KvTxneikm2AEkq96W0x2toui4Tenkuz3DF+o0yVKQxGThz1RKsui+DfgTloJsrNxO9hVamfdEM57zY=,iv:YXZU83xHCydhYA3NLjAi0CZz97o9Apb9Xd6/uMLBuZU=,tag:hO2BFbbVKFW4fOIRAPszfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
