apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:LYO0XkhKD5l/Lri6sAM7iKEMHF+WKgng0itgcx154196+yXJ0Mb01u9LgV4M1ax7DjhYtDVRmCYl680M,iv:4Q+6QOIOhWiPnOJ1lSOWa3UfIi6z938olrvcd9xdIG0=,tag:9vgNTCroGHd5S8Uz1QrDSw==,type:str]
    username: ENC[AES256_GCM,data:2sf7Pdc=,iv:e96+ZLIHbnrD047u65Wh033bCr9H0QM54GMwBCanoDE=,tag:17hPGQTVoozvhf9p5N3M1w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aG5lVUxhVE5Lc0JTbzVi
            ZEdLTVBJRDNZVEdyUmFaMGE2YWMyWG9UMnpnCkRJZ1RoRVVRUWpaVmZZSGNnaVJ6
            UnJKNGdNN2JLOEJndWMrSVVqWXpXajAKLS0tIFV3K0t3eGgzd05ocVQxbFJDZHg0
            L3RSTmpBeWVwNGZ1S281STF0WFR2bTgK9ZrHfFCFBbYj3QEE/TqnHsWwwxoybyV4
            4tRnXwpEsNjvEoUyM+gCbUh5LIkbFg1nY9TuV5fMBO43Cd/ieI4gvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T23:25:09Z"
    mac: ENC[AES256_GCM,data:mda4418CTHKzMVya8yCsWYbvQROWofvRT5hmC8aAF+xFrBitqDsR5wP7h34e9FW4fVYJx9bbek5/U27AZIlHveCucUSIT/0+bCaGXlxt0fBDpHKdf10pur0aqEMSjEfpYgJks7uHMZSAkBAkawZv2A1AP4J+G+ZZ2leoXdXu42Q=,iv:FshAnlQ+sn/8AVpbLA0jgR3+sKns2cmv7Eu4tNS9p3Q=,tag:AFtm99cL2a63YssARDLMKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
