apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Orupp2O/aFrG8Wo+,iv:8oIMcLVHcmepZGxflP22ZXrOiE7udQvQX5B2idyA198=,tag:ghO1SYJXaOHbo9yqPL0ZHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dla5z3z8elyf9apv4datwxfu84zz5hdy3fegw9fqe4a0az47npkqrgh5te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VUNCWlp2RU5RZFBxTHds
            YjVqeTQvUXl5N0F3UEhCUlZudnhEM0xjc2lFCkMycjl6M2twbVUyeWdxMFZkWEFm
            OVdYZTdpUWZSRTQ5b3hYcGtiQjNYZkkKLS0tIHY5YnFDeTNad2FoUnNkR1R0enRG
            ZEtkMTkzczd6ZG1XR09pR0pPMnVueTAKh7gHnqbELFmLQ9gr1qYlNFJMSKBRujEP
            DrTIsjkEyhW72bJIYUbG/qhUwQYAODlEsUoGhhG8eBKuF4DanrNzSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T11:05:47Z"
    mac: ENC[AES256_GCM,data:sKTVNH5dB+CuCpMojkRV9DjnF6k8uzAZlj6a10zKJZ9lrsXhrf5M1vKcXwP+uJ+dKu0WodIF8kjfLJZm0n3+ST2ItWMWD14z9LqRX9vzqXT30xQTsXMslG2TrJuXhZA5+MzVr0getF4QfuIV+1RE9NQaEj35h6du5hK9CQERciI=,iv:5L6NbRwXGh6JRpYRDtNXihWXG9NHoXKY1HL94ME80LI=,tag:4o4+sDkgczQYbBKdrs3hXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
