apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secrets
spec:
  target:
    name: sonarr-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__POSTGRES_USER: |-
          {{ .SONARR__POSTGRES_USER }}
        SONARR__POSTGRES_PASSWORD: |-
          {{ .SONARR__POSTGRES_PASSWORD }}
        SONARR__POSTGRES_PORT: |-
          {{ .SONARR__POSTGRES_PORT }}
        SONARR__POSTGRES_HOST: |-
          {{ .SONARR__POSTGRES_HOST }}
  data:
    - secretKey: SONARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: SONARR__POSTGRES_USER
        property: SONARR__POSTGRES_USER

    - secretKey: SONARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: SONARR__POSTGRES_PASSWORD
        property: SONARR__POSTGRES_PASSWORD

    - secretKey: SONARR__POSTGRES_PORT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: SONARR__POSTGRES_PORT
        property: SONARR__POSTGRES_PORT

    - secretKey: SONARR__POSTGRES_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: SONARR__POSTGRES_HOST
        property: SONARR__POSTGRES_HOST