---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tank-nfs
  volumeName: qbittorrent-config-pv
  resources:
    requests:
      storage: 100Mi